version: "3.3"
services:
  server:
    container_name: server
    build: ./my-shop-server
    image: server:dev
    ports:
      - "8081:8081"
  react:
    container_name: react
    build: ./my-shop
    image: react:dev
    ports:
      - "3001:3001"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    depends_on:
      - server
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    stdin_open: true
    tty: true
#  Mongo dependecy not added yet. DB calls made to Atlas
#     depends_on:
#       - mongo
#   mongo:
#     image: mongo
#     ports:
#       - '27017:27017'

